	/*-----------------------------------------------------------------------------------------
	--      SYSTEM                     : STR_GMG      
	--      AUTHOR                     : Prabodh Tripathi(qa)                                        
	--      2013-10-17                 : INITIAL VERSION
	--      PURPOSE                    : MONTHLY DATA VALIDATION
	-----------------------------------------------------------------------------------------*/
	
--Verify threshold metric values (<65) for "SYWR Transaction  %"
SELECT STR_GMG_LOCN_NBR 
FROM STR_GMG_RPT_VIEWS_PRD.FACT_SRS_STR_GMG_COMPET_MTHLY

WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)
AND MTH_NBR = (SELECT MTH_NO FROM TEMPPARM)
AND STR_GMG_METRIC_VALU_AMT < (SELECT ATTR_CONFIG_FACTOR_VALU FROM STR_GMG_RPT_VIEWS_PRD.REF_STR_GMG_GENRC_CONFIG WHERE
ATTR_NM = 'SYWR_TRAN_PCT_IMPRV' AND ATTR_GRP_NM = (SELECT FMT_CD FROM TEMPPARM))

AND STR_GMG_COMPET_KEY IN

(
SELECT STR_GMG_COMPET_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_COMPET 
WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)  
AND STR_GMG_COMPET_STA_MTH_NBR = (SELECT MTH_NO FROM TEMPPARM) AND STR_GMG_COMPET_LVL_CD = 'S'
)

AND STR_GMG_COMPET_RNK_LVL_CD = 'F'
AND STR_GMG_METRIC_KEY IN ( SELECT STR_GMG_METRIC_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_METRIC WHERE STR_GMG_METRIC_NM = 'SYWR_PNTRT_PCT' AND STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM))
AND STR_GMG_COMPET_METRIC_KEY IN
(
SELECT STR_GMG_COMPET_METRIC_KEY FROM STR_GMG_RPT_VIEWS_PRD.REF_STR_GMG_COMPET_METRIC 
WHERE 
STR_GMG_COMPET_KEY IN (SELECT STR_GMG_COMPET_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_COMPET 
WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)  AND STR_GMG_COMPET_STA_MTH_NBR = (SELECT MTH_NO FROM TEMPPARM) AND STR_GMG_COMPET_LVL_CD = 'S'
)
AND STR_GMG_METRIC_KEY IN ( SELECT STR_GMG_METRIC_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_METRIC WHERE STR_GMG_METRIC_NM = 'SYWR_PNTRT_PCT' AND STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM))
AND STR_GMG_COMPET_WT_PCT <> 0
)

AND STR_GMG_LOCN_NBR in

(SELECT STR_GMG_LOCN_NBR FROM STR_GMG_RPT_VIEWS_PRD.FACT_SRS_STR_GMG_COMPET_MTHLY
WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)
AND MTH_NBR = (SELECT MTH_NO FROM TEMPPARM)
AND STR_GMG_COMPET_KEY IN

(
SELECT STR_GMG_COMPET_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_COMPET 
WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)  AND STR_GMG_COMPET_STA_MTH_NBR = (SELECT MTH_NO FROM TEMPPARM) AND STR_GMG_COMPET_LVL_CD = 'S'
)

AND STR_GMG_COMPET_RNK_LVL_CD = 'F'
AND STR_GMG_METRIC_KEY IN ( SELECT STR_GMG_METRIC_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_METRIC 
WHERE STR_GMG_METRIC_NM = 'SYWR_TRAN_PCT_IMPRV' AND STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM))
AND STR_GMG_METRIC_RNK = 9999
)

MINUS

SELECT STR_GMG_LOCN_NBR FROM STR_GMG_RPT_VIEWS_PRD.FACT_SRS_STR_GMG_COMPET_MTHLY
WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)
AND MTH_NBR = (SELECT MTH_NO FROM TEMPPARM)
AND STR_GMG_COMPET_KEY IN

(
SELECT STR_GMG_COMPET_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_COMPET 
WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)  AND STR_GMG_COMPET_STA_MTH_NBR = (SELECT MTH_NO FROM TEMPPARM) AND STR_GMG_COMPET_LVL_CD = 'S'
)

AND STR_GMG_COMPET_RNK_LVL_CD = 'F'
AND STR_GMG_METRIC_KEY IN ( SELECT STR_GMG_METRIC_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_METRIC WHERE STR_GMG_METRIC_NM = 'SYWR_TRAN_PCT_IMPRV' AND STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM))
AND STR_GMG_METRIC_RNK = 9999
;