	/*-----------------------------------------------------------------------------------------
	--      SYSTEM                     : STR_GMG      
	--      AUTHOR                     : Prabodh Tripathi(qa)                                        
	--      2013-10-17                 : INITIAL VERSION
	--      PURPOSE                    : MONTHLY DATA VALIDATION
	-----------------------------------------------------------------------------------------*/

--Validate the number of Metrics participating in UMR competition
SELECT STR_GMG_METRIC_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_METRIC 
WHERE
STR_GMG_METRIC_KEY IN
( SELECT STR_GMG_METRIC_KEY FROM STR_GMG_RPT_VIEWS_PRD.REF_STR_GMG_COMPET_METRIC WHERE STR_GMG_COMPET_KEY IN

(
SELECT STR_GMG_COMPET_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_COMPET 
WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)  AND STR_GMG_COMPET_STA_MTH_NBR = (SELECT MTH_NO FROM TEMPPARM) AND STR_GMG_COMPET_LVL_CD = 'S'
)

)
AND STR_GMG_METRIC_STAT_IND = 'A' AND STR_GMG_METRIC_PROC_PRTY_NBR = 2

MINUS

SELECT DISTINCT STR_GMG_METRIC_KEY FROM STR_GMG_RPT_VIEWS_PRD.FACT_SRS_STR_GMG_COMPET_MTHLY
WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)
AND MTH_NBR = (SELECT MTH_NO FROM TEMPPARM)
AND STR_GMG_COMPET_KEY IN
(
SELECT STR_GMG_COMPET_KEY FROM STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_COMPET 
WHERE STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)  AND STR_GMG_COMPET_STA_MTH_NBR = (SELECT MTH_NO FROM TEMPPARM) AND STR_GMG_COMPET_LVL_CD = 'S'
)
AND STR_GMG_COMPET_RNK_LVL_CD = 'F'
;
