	/*-----------------------------------------------------------------------------------------
	--      SYSTEM                     : STR_GMG                                                 
	--      AUTHOR                     : Prabodh Tripathi(qa)                                        
	--      2013-10-21                 : INITIAL VERSION
	--      PURPOSE                    : MONTHLY DATA VALIDATION
	-----------------------------------------------------------------------------------------*/
--Verify that missing metrics have ZERO metrics value and weighted pct & metrics rank as last rank incremented by one
--Missing  metrics for rank as LAST plus 1 metrics rank, metrics value as ZERO and metric wt pct as ZERO

SELECT	
STR_GMG_METRIC_KEY,
STR_GMG_METRIC_VALU_AMT,
STR_GMG_METRIC_WT_PCT,
STR_GMG_METRIC_RNK

FROM	STR_GMG_RPT_VIEWS_PRD.FACT_SRS_STR_GMG_COMPET_MTHLY
WHERE	STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)
	AND	MTH_NBR = (SELECT MTH_NO FROM TEMPPARM)
	AND	STR_GMG_COMPET_KEY IN

(
SELECT	STR_GMG_COMPET_KEY 
FROM	STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_COMPET 
WHERE	STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)  
	AND	STR_GMG_COMPET_STA_MTH_NBR = (SELECT MTH_NO FROM TEMPPARM) 
	AND	STR_GMG_COMPET_LVL_CD = 'S'
)

	AND	STR_GMG_COMPET_RNK_LVL_CD = 'F'

	AND	(STR_GMG_METRIC_KEY, STR_GMG_LOCN_NBR)  IN
(
SELECT	STR_GMG_METRIC_KEY, STR_GMG_LOCN_NBR  
FROM	STR_GMG_RPT_VIEWS_PRD.AUDSTRGMGMISNGCOMPETMETRICMTH 
WHERE	MTH_NBR = (SELECT MTH_NO FROM TEMPPARM)
	AND	STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)
	AND	STR_GMG_METRIC_KEY IN 

( 
SELECT	STR_GMG_METRIC_KEY 
FROM	STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_METRIC 
WHERE	
STR_GMG_METRIC_KEY IN
( 
SELECT	STR_GMG_METRIC_KEY 
FROM	STR_GMG_RPT_VIEWS_PRD.REF_STR_GMG_COMPET_METRIC 
WHERE	STR_GMG_COMPET_KEY IN

(
SELECT	STR_GMG_COMPET_KEY 
FROM	STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_COMPET 
WHERE	STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)  
	AND	STR_GMG_COMPET_STA_MTH_NBR = (SELECT MTH_NO FROM TEMPPARM) 
	AND	STR_GMG_COMPET_LVL_CD = 'S'
)

)
	AND	STR_GMG_METRIC_STAT_IND = 'A' 
	AND	STR_GMG_METRIC_PROC_PRTY_NBR = 2  
)

)

GROUP BY 1,2,3,4



MINUS	



SELECT	
A.STR_GMG_METRIC_KEY,
0 STR_GMG_METRIC_VALU_AMT,
0 STR_GMG_METRIC_WT_PCT,
A.STR_GMG_METRIC_RNK_PLUS_ONE
FROM	

(



SELECT	 
STR_GMG_METRIC_KEY,

(CASE WHEN MAX(STR_GMG_METRIC_MTHLY_VALU_RNK) = 9999 THEN 9999 ELSE (MAX(STR_GMG_METRIC_MTHLY_VALU_RNK) + 1) END )  STR_GMG_METRIC_RNK_PLUS_ONE

FROM	STR_GMG_RPT_VIEWS_PRD.FACTSTRGMGADHOCLOCNRNKMTHLY

WHERE	

                STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)
	AND	MTH_NBR = (SELECT MTH_NO FROM TEMPPARM)
	AND	STR_GMG_COMPET_RNK_LVL_CD = 'F'

	AND	(STR_GMG_METRIC_KEY)   IN
(
SELECT	STR_GMG_METRIC_KEY 
FROM	STR_GMG_RPT_VIEWS_PRD.AUDSTRGMGMISNGCOMPETMETRICMTH 
WHERE	MTH_NBR = (SELECT MTH_NO FROM TEMPPARM)
	AND	STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)
	AND	STR_GMG_METRIC_KEY IN 
( 
SELECT	STR_GMG_METRIC_KEY 
FROM	STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_METRIC 
WHERE	
STR_GMG_METRIC_KEY IN
( 
SELECT	STR_GMG_METRIC_KEY 
FROM	STR_GMG_RPT_VIEWS_PRD.REF_STR_GMG_COMPET_METRIC 
WHERE	STR_GMG_COMPET_KEY IN

(
SELECT	STR_GMG_COMPET_KEY 
FROM	STR_GMG_RPT_VIEWS_PRD.LU_STR_GMG_COMPET 
WHERE	STR_GMG_STR_FMT_CD = (SELECT FMT_CD FROM TEMPPARM)  
	AND	STR_GMG_COMPET_STA_MTH_NBR = (SELECT MTH_NO FROM TEMPPARM) 
	AND	STR_GMG_COMPET_LVL_CD = 'S'
)

)
	AND	STR_GMG_METRIC_STAT_IND = 'A' 
	AND	STR_GMG_METRIC_PROC_PRTY_NBR = 2  
)
)

GROUP BY 1

) A